name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-pdf:
    name: Create the PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-base
      - name: Run pdflatex
        run: pdflatex --shell-escape requirements.tex
